services:
  - type: web
    name: good-shepherd-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: good-shepherd-db
          property: connectionString

databases:
  - name: good-shepherd-db
    plan: free
