"use strict";

const SCHEMA_BASELINE_VERSION = "2026-09-06-production-schema-baseline-v1";

const REQUIRED_TABLES = [
  "ai_action_logs",
  "ai_dashboard_cache",
  "cameras",
  "candidate_history_evidence_events",
  "customer_push_devices",
  "customer_sessions",
  "device_mappings",
  "firmware_releases",
  "human_presence_behavioral_observations",
  "human_presence_behavioral_pattern_analyses",
  "human_presence_candidate_interpretations",
  "human_presence_decision_readiness",
  "human_presence_episode_profile_analyses",
  "human_presence_firmware_releases",
  "monitoring_audit_log",
  "monitoring_case_events",
  "monitoring_cases",
  "monitoring_operators",
  "monitoring_sessions",
  "motion_events",
  "node_commands",
  "node_health",
  "nodes",
  "resident_activity_daily",
  "resident_checkins",
  "residents",
  "sensors",
  "webhook_events"
];

const REQUIRED_COLUMNS = [
  [
    "ai_action_logs",
    "id"
  ],
  [
    "ai_action_logs",
    "resident_id"
  ],
  [
    "ai_dashboard_cache",
    "cache_key"
  ],
  [
    "ai_dashboard_cache",
    "generated_at"
  ],
  [
    "ai_dashboard_cache",
    "payload"
  ],
  [
    "ai_dashboard_cache",
    "updated_at"
  ],
  [
    "cameras",
    "created_at"
  ],
  [
    "cameras",
    "deleted_at"
  ],
  [
    "cameras",
    "id"
  ],
  [
    "cameras",
    "is_deleted"
  ],
  [
    "cameras",
    "resident_id"
  ],
  [
    "cameras",
    "source_key"
  ],
  [
    "cameras",
    "source_name"
  ],
  [
    "cameras",
    "updated_at"
  ],
  [
    "candidate_history_evidence_events",
    "dimensions"
  ],
  [
    "candidate_history_evidence_events",
    "episode_id"
  ],
  [
    "candidate_history_evidence_events",
    "event_id"
  ],
  [
    "candidate_history_evidence_events",
    "event_payload"
  ],
  [
    "candidate_history_evidence_events",
    "evidence_schema_version"
  ],
  [
    "candidate_history_evidence_events",
    "history_count"
  ],
  [
    "candidate_history_evidence_events",
    "location_name"
  ],
  [
    "candidate_history_evidence_events",
    "node_id"
  ],
  [
    "candidate_history_evidence_events",
    "prior_count"
  ],
  [
    "candidate_history_evidence_events",
    "protocol_version"
  ],
  [
    "candidate_history_evidence_events",
    "received_at"
  ],
  [
    "candidate_history_evidence_events",
    "resident_name"
  ],
  [
    "candidate_history_evidence_events",
    "software_version"
  ],
  [
    "candidate_history_evidence_events",
    "source_key"
  ],
  [
    "candidate_history_evidence_events",
    "source_name"
  ],
  [
    "customer_push_devices",
    "apns_environment"
  ],
  [
    "customer_push_devices",
    "id"
  ],
  [
    "customer_push_devices",
    "resident_id"
  ],
  [
    "customer_sessions",
    "resident_id"
  ],
  [
    "customer_sessions",
    "token_hash"
  ],
  [
    "device_mappings",
    "default_alert_level"
  ],
  [
    "device_mappings",
    "default_time_text"
  ],
  [
    "device_mappings",
    "resident_name"
  ],
  [
    "device_mappings",
    "source_key"
  ],
  [
    "device_mappings",
    "source_name"
  ],
  [
    "firmware_releases",
    "created_at"
  ],
  [
    "firmware_releases",
    "created_by"
  ],
  [
    "firmware_releases",
    "firmware_url"
  ],
  [
    "firmware_releases",
    "firmware_version"
  ],
  [
    "firmware_releases",
    "id"
  ],
  [
    "firmware_releases",
    "is_active"
  ],
  [
    "firmware_releases",
    "release_notes"
  ],
  [
    "firmware_releases",
    "sha256"
  ],
  [
    "human_presence_behavioral_observations",
    "assignment_authority"
  ],
  [
    "human_presence_behavioral_observations",
    "authoritative_resident_id"
  ],
  [
    "human_presence_behavioral_observations",
    "authoritative_resident_name"
  ],
  [
    "human_presence_behavioral_observations",
    "authoritative_room_or_location"
  ],
  [
    "human_presence_behavioral_observations",
    "authoritative_sensor_id"
  ],
  [
    "human_presence_behavioral_observations",
    "authority_resolution_status"
  ],
  [
    "human_presence_behavioral_observations",
    "behavioral_observation_at"
  ],
  [
    "human_presence_behavioral_observations",
    "behavioral_observation_payload"
  ],
  [
    "human_presence_behavioral_observations",
    "behavioral_observation_version"
  ],
  [
    "human_presence_behavioral_observations",
    "decision_readiness_at"
  ],
  [
    "human_presence_behavioral_observations",
    "decision_readiness_version"
  ],
  [
    "human_presence_behavioral_observations",
    "evidence_event_id"
  ],
  [
    "human_presence_behavioral_observations",
    "evidence_received_at"
  ],
  [
    "human_presence_behavioral_observations",
    "interpretation_version"
  ],
  [
    "human_presence_behavioral_observations",
    "interpreted_at"
  ],
  [
    "human_presence_behavioral_pattern_analyses",
    "assignment_authority"
  ],
  [
    "human_presence_behavioral_pattern_analyses",
    "authoritative_resident_id"
  ],
  [
    "human_presence_behavioral_pattern_analyses",
    "authoritative_resident_name"
  ],
  [
    "human_presence_behavioral_pattern_analyses",
    "authoritative_room_or_location"
  ],
  [
    "human_presence_behavioral_pattern_analyses",
    "authoritative_sensor_id"
  ],
  [
    "human_presence_behavioral_pattern_analyses",
    "authority_resolution_status"
  ],
  [
    "human_presence_behavioral_pattern_analyses",
    "behavioral_observation_at"
  ],
  [
    "human_presence_behavioral_pattern_analyses",
    "behavioral_observation_version"
  ],
  [
    "human_presence_behavioral_pattern_analyses",
    "behavioral_pattern_analysis_at"
  ],
  [
    "human_presence_behavioral_pattern_analyses",
    "behavioral_pattern_analysis_payload"
  ],
  [
    "human_presence_behavioral_pattern_analyses",
    "behavioral_pattern_analysis_version"
  ],
  [
    "human_presence_behavioral_pattern_analyses",
    "decision_readiness_at"
  ],
  [
    "human_presence_behavioral_pattern_analyses",
    "decision_readiness_version"
  ],
  [
    "human_presence_behavioral_pattern_analyses",
    "evidence_event_id"
  ],
  [
    "human_presence_behavioral_pattern_analyses",
    "evidence_received_at"
  ],
  [
    "human_presence_behavioral_pattern_analyses",
    "interpretation_version"
  ],
  [
    "human_presence_behavioral_pattern_analyses",
    "interpreted_at"
  ],
  [
    "human_presence_candidate_interpretations",
    "assignment_authority"
  ],
  [
    "human_presence_candidate_interpretations",
    "authoritative_resident_id"
  ],
  [
    "human_presence_candidate_interpretations",
    "authoritative_resident_name"
  ],
  [
    "human_presence_candidate_interpretations",
    "authoritative_room_or_location"
  ],
  [
    "human_presence_candidate_interpretations",
    "authoritative_sensor_id"
  ],
  [
    "human_presence_candidate_interpretations",
    "authority_resolution_status"
  ],
  [
    "human_presence_candidate_interpretations",
    "evidence_event_id"
  ],
  [
    "human_presence_candidate_interpretations",
    "evidence_received_at"
  ],
  [
    "human_presence_candidate_interpretations",
    "interpretation_payload"
  ],
  [
    "human_presence_candidate_interpretations",
    "interpretation_version"
  ],
  [
    "human_presence_candidate_interpretations",
    "interpreted_at"
  ],
  [
    "human_presence_candidate_interpretations",
    "node_id"
  ],
  [
    "human_presence_candidate_interpretations",
    "source_key"
  ],
  [
    "human_presence_decision_readiness",
    "assignment_authority"
  ],
  [
    "human_presence_decision_readiness",
    "authoritative_resident_id"
  ],
  [
    "human_presence_decision_readiness",
    "authoritative_resident_name"
  ],
  [
    "human_presence_decision_readiness",
    "authoritative_room_or_location"
  ],
  [
    "human_presence_decision_readiness",
    "authoritative_sensor_id"
  ],
  [
    "human_presence_decision_readiness",
    "authority_resolution_status"
  ],
  [
    "human_presence_decision_readiness",
    "decision_readiness_at"
  ],
  [
    "human_presence_decision_readiness",
    "decision_readiness_payload"
  ],
  [
    "human_presence_decision_readiness",
    "decision_readiness_version"
  ],
  [
    "human_presence_decision_readiness",
    "evidence_event_id"
  ],
  [
    "human_presence_decision_readiness",
    "evidence_received_at"
  ],
  [
    "human_presence_decision_readiness",
    "interpretation_version"
  ],
  [
    "human_presence_decision_readiness",
    "interpreted_at"
  ],
  [
    "human_presence_episode_profile_analyses",
    "assignment_authority"
  ],
  [
    "human_presence_episode_profile_analyses",
    "authoritative_resident_id"
  ],
  [
    "human_presence_episode_profile_analyses",
    "authoritative_resident_name"
  ],
  [
    "human_presence_episode_profile_analyses",
    "authoritative_room_or_location"
  ],
  [
    "human_presence_episode_profile_analyses",
    "authoritative_sensor_id"
  ],
  [
    "human_presence_episode_profile_analyses",
    "authority_resolution_status"
  ],
  [
    "human_presence_episode_profile_analyses",
    "episode_profile_analysis_at"
  ],
  [
    "human_presence_episode_profile_analyses",
    "episode_profile_analysis_payload"
  ],
  [
    "human_presence_episode_profile_analyses",
    "episode_profile_analysis_version"
  ],
  [
    "human_presence_episode_profile_analyses",
    "evidence_event_id"
  ],
  [
    "human_presence_episode_profile_analyses",
    "evidence_received_at"
  ],
  [
    "human_presence_episode_profile_analyses",
    "evidence_schema_version"
  ],
  [
    "human_presence_firmware_releases",
    "created_at"
  ],
  [
    "human_presence_firmware_releases",
    "created_by"
  ],
  [
    "human_presence_firmware_releases",
    "firmware_url"
  ],
  [
    "human_presence_firmware_releases",
    "firmware_version"
  ],
  [
    "human_presence_firmware_releases",
    "id"
  ],
  [
    "human_presence_firmware_releases",
    "is_active"
  ],
  [
    "human_presence_firmware_releases",
    "release_notes"
  ],
  [
    "human_presence_firmware_releases",
    "sha256"
  ],
  [
    "monitoring_audit_log",
    "id"
  ],
  [
    "monitoring_audit_log",
    "operator_id"
  ],
  [
    "monitoring_case_events",
    "case_id"
  ],
  [
    "monitoring_case_events",
    "id"
  ],
  [
    "monitoring_cases",
    "handoff_reason"
  ],
  [
    "monitoring_cases",
    "handoff_requested_at"
  ],
  [
    "monitoring_cases",
    "handoff_requested_by_operator_id"
  ],
  [
    "monitoring_cases",
    "handoff_requested_by_operator_name"
  ],
  [
    "monitoring_cases",
    "handoff_to_operator_id"
  ],
  [
    "monitoring_cases",
    "handoff_to_operator_name"
  ],
  [
    "monitoring_cases",
    "id"
  ],
  [
    "monitoring_cases",
    "resident_id"
  ],
  [
    "monitoring_cases",
    "resident_response_at"
  ],
  [
    "monitoring_cases",
    "resident_response_code"
  ],
  [
    "monitoring_cases",
    "resident_response_label"
  ],
  [
    "monitoring_cases",
    "signal_cleared_at"
  ],
  [
    "monitoring_operators",
    "activation_created_at"
  ],
  [
    "monitoring_operators",
    "activation_expires_at"
  ],
  [
    "monitoring_operators",
    "activation_token_hash"
  ],
  [
    "monitoring_operators",
    "activation_used_at"
  ],
  [
    "monitoring_operators",
    "created_at"
  ],
  [
    "monitoring_operators",
    "display_name"
  ],
  [
    "monitoring_operators",
    "id"
  ],
  [
    "monitoring_operators",
    "is_active"
  ],
  [
    "monitoring_operators",
    "is_bootstrap"
  ],
  [
    "monitoring_operators",
    "is_enrolled"
  ],
  [
    "monitoring_operators",
    "must_change_password"
  ],
  [
    "monitoring_operators",
    "password_hash"
  ],
  [
    "monitoring_operators",
    "role"
  ],
  [
    "monitoring_operators",
    "totp_secret_encrypted"
  ],
  [
    "monitoring_operators",
    "username"
  ],
  [
    "monitoring_sessions",
    "operator_id"
  ],
  [
    "monitoring_sessions",
    "token_hash"
  ],
  [
    "motion_events",
    "id"
  ],
  [
    "motion_events",
    "resident_id"
  ],
  [
    "motion_events",
    "webhook_event_id"
  ],
  [
    "node_commands",
    "command_id"
  ],
  [
    "node_commands",
    "command_type"
  ],
  [
    "node_commands",
    "node_id"
  ],
  [
    "node_commands",
    "payload"
  ],
  [
    "node_commands",
    "requested_at"
  ],
  [
    "node_commands",
    "requested_by"
  ],
  [
    "node_commands",
    "status"
  ],
  [
    "node_health",
    "active_monitor_count"
  ],
  [
    "node_health",
    "camera_count"
  ],
  [
    "node_health",
    "camera_summary"
  ],
  [
    "node_health",
    "checked_in_at"
  ],
  [
    "node_health",
    "diagnostics"
  ],
  [
    "node_health",
    "ffmpeg_path"
  ],
  [
    "node_health",
    "ffmpeg_status"
  ],
  [
    "node_health",
    "hostname"
  ],
  [
    "node_health",
    "last_error"
  ],
  [
    "node_health",
    "last_error_at"
  ],
  [
    "node_health",
    "local_config_port"
  ],
  [
    "node_health",
    "local_ip"
  ],
  [
    "node_health",
    "location_name"
  ],
  [
    "node_health",
    "monitor_status"
  ],
  [
    "node_health",
    "node_id"
  ],
  [
    "node_health",
    "node_name"
  ],
  [
    "node_health",
    "platform"
  ],
  [
    "node_health",
    "setup_state"
  ],
  [
    "node_health",
    "software_version"
  ],
  [
    "node_health",
    "uptime_seconds"
  ],
  [
    "node_health",
    "wifi_rssi"
  ],
  [
    "node_health",
    "wifi_ssid"
  ],
  [
    "nodes",
    "archived_at"
  ],
  [
    "nodes",
    "archived_reason"
  ],
  [
    "nodes",
    "camera_count"
  ],
  [
    "nodes",
    "camera_summary"
  ],
  [
    "nodes",
    "first_seen_at"
  ],
  [
    "nodes",
    "is_archived"
  ],
  [
    "nodes",
    "local_config_port"
  ],
  [
    "nodes",
    "local_ip"
  ],
  [
    "nodes",
    "location_name"
  ],
  [
    "nodes",
    "node_id"
  ],
  [
    "nodes",
    "node_name"
  ],
  [
    "nodes",
    "setup_state"
  ],
  [
    "nodes",
    "software_version"
  ],
  [
    "nodes",
    "status"
  ],
  [
    "nodes",
    "wifi_rssi"
  ],
  [
    "nodes",
    "wifi_ssid"
  ],
  [
    "resident_activity_daily",
    "resident_id"
  ],
  [
    "resident_checkins",
    "id"
  ],
  [
    "resident_checkins",
    "resident_id"
  ],
  [
    "residents",
    "access_code"
  ],
  [
    "residents",
    "active_warnings"
  ],
  [
    "residents",
    "alert_level"
  ],
  [
    "residents",
    "created_at"
  ],
  [
    "residents",
    "deleted_at"
  ],
  [
    "residents",
    "id"
  ],
  [
    "residents",
    "is_deleted"
  ],
  [
    "residents",
    "last_activity"
  ],
  [
    "residents",
    "location"
  ],
  [
    "residents",
    "name"
  ],
  [
    "residents",
    "status_text"
  ],
  [
    "residents",
    "updated_at"
  ],
  [
    "sensors",
    "assignment_authority"
  ],
  [
    "sensors",
    "created_at"
  ],
  [
    "sensors",
    "deleted_at"
  ],
  [
    "sensors",
    "id"
  ],
  [
    "sensors",
    "is_active"
  ],
  [
    "sensors",
    "is_deleted"
  ],
  [
    "sensors",
    "location_name"
  ],
  [
    "sensors",
    "node_id"
  ],
  [
    "sensors",
    "resident_id"
  ],
  [
    "sensors",
    "resident_name"
  ],
  [
    "sensors",
    "room_name"
  ],
  [
    "sensors",
    "sensor_type"
  ],
  [
    "sensors",
    "setup_state"
  ],
  [
    "sensors",
    "source_key"
  ],
  [
    "sensors",
    "source_name"
  ],
  [
    "sensors",
    "updated_at"
  ],
  [
    "webhook_events",
    "acknowledged"
  ],
  [
    "webhook_events",
    "acknowledged_at"
  ],
  [
    "webhook_events",
    "alert_level"
  ],
  [
    "webhook_events",
    "event_payload"
  ],
  [
    "webhook_events",
    "event_type"
  ],
  [
    "webhook_events",
    "id"
  ],
  [
    "webhook_events",
    "location_name"
  ],
  [
    "webhook_events",
    "message"
  ],
  [
    "webhook_events",
    "node_id"
  ],
  [
    "webhook_events",
    "resident_name"
  ],
  [
    "webhook_events",
    "resolution_note"
  ],
  [
    "webhook_events",
    "sensor_type"
  ],
  [
    "webhook_events",
    "source_key"
  ],
  [
    "webhook_events",
    "source_name"
  ],
  [
    "webhook_events",
    "time_text"
  ],
  [
    "webhook_events",
    "timestamp"
  ]
];

const REQUIRED_INDEXES = [
  "ai_action_logs_created_at_idx",
  "ai_action_logs_resident_id_created_at_idx",
  "ai_action_logs_resident_name_created_at_idx",
  "cameras_assigned_node_id_idx",
  "cameras_is_deleted_idx",
  "cameras_resident_id_idx",
  "candidate_history_evidence_node_received_idx",
  "candidate_history_evidence_source_received_idx",
  "customer_push_devices_resident_idx",
  "customer_push_devices_token_environment_unique_idx",
  "customer_sessions_expires_at_idx",
  "customer_sessions_resident_id_idx",
  "firmware_releases_created_at_idx",
  "firmware_releases_is_active_idx",
  "human_presence_behavioral_pattern_resident_room_time_idx",
  "human_presence_candidate_interpretations_node_time_idx",
  "human_presence_candidate_interpretations_resident_time_idx",
  "human_presence_decision_readiness_resident_time_idx",
  "human_presence_decision_readiness_sensor_time_idx",
  "human_presence_episode_profile_resident_room_time_idx",
  "human_presence_firmware_releases_created_at_idx",
  "human_presence_firmware_releases_is_active_idx",
  "idx_hp_behavioral_observations_resident_room_time",
  "monitoring_audit_log_created_at_idx",
  "monitoring_audit_log_operator_id_idx",
  "monitoring_case_events_case_idx",
  "monitoring_cases_one_active_per_resident_idx",
  "monitoring_cases_resident_idx",
  "monitoring_cases_status_idx",
  "monitoring_operators_activation_token_idx",
  "monitoring_operators_username_unique_idx",
  "monitoring_sessions_expires_at_idx",
  "monitoring_sessions_operator_id_idx",
  "motion_events_event_timestamp_idx",
  "motion_events_resident_id_timestamp_idx",
  "motion_events_resident_name_timestamp_idx",
  "motion_events_source_key_timestamp_idx",
  "motion_events_webhook_event_id_unique_idx",
  "node_commands_node_id_status_idx",
  "node_commands_requested_at_idx",
  "node_health_checked_in_at_idx",
  "node_health_monitor_status_idx",
  "resident_activity_daily_date_idx",
  "resident_checkins_case_idx",
  "resident_checkins_pending_idx",
  "resident_checkins_resident_idx",
  "residents_access_code_unique_idx",
  "residents_is_deleted_idx",
  "sensors_is_deleted_idx",
  "sensors_node_id_idx",
  "sensors_resident_id_idx",
  "sensors_source_key_unique_idx",
  "webhook_events_event_type_timestamp_idx",
  "webhook_events_source_key_event_type_timestamp_idx"
];

module.exports = {
  SCHEMA_BASELINE_VERSION,
  REQUIRED_TABLES,
  REQUIRED_COLUMNS,
  REQUIRED_INDEXES
};
